#!/bin/bash

printenv | sed 's/^\([^=]*\)\=\(.*\)$/\1\="\2"/g' | sed 's/^\(_\)\=\(.*\)$//g' > /app/.env.prod.local
envsubst < /etc/youtube-dl.conf > /etc/youtube-dl.conf
envsubst < /etc/supervisor.d/messenger.ini > /etc/supervisor.d/messenger.ini

# Prepare prod env
php /app/bin/console cache:clear -e prod --no-debug
chmod -R 0777 /app/var/

# Configure and start supervisor
supervisord -c /etc/supervisord.conf

# Start cron
/usr/sbin/crond -b -l 8 -L /dev/stdout

# Start PHP-FPM daemon
php-fpm
