#!/bin/bash

printenv | sed 's/^\([^=]*\)\=\(.*\)$/\1\="\2"/g' | sed 's/^\(_\)\=\(.*\)$//g' > /app/.env.prod.local

# Prepare prod env
php /app/bin/console cache:clear -e prod --no-debug
chmod -R 0777 /app/var/

envsubst < /etc/youtube-dl.conf > /etc/youtube-dl.conf

# Configure and start supervisor
envsubst < /etc/supervisor/conf.d/messenger.conf > /etc/supervisor/conf.d/messenger.conf
supervisord -c /etc/supervisor/supervisord.conf

# start cron
cron -l -L 8

# Start PHP-FPM daemon
php-fpm
